package com.shudun.dms.processor;

import com.shudun.dms.properties.HsmInfoProcessor;

//@Component
public class KmsHsmInfoProcessor implements HsmInfoProcessor {
    @Override
    public String getIp() {
        return "127.0.0.1";
    }

    @Override
    public int getPort() {
        return 10197;
    }

    @Override
    public String getDestId() {
        return "22222222222222222222222222222222";
    }

    @Override
    public String getSourceId() {
        return "11111111111111111111111111111111";
    }

    @Override
    public String getLocalSignPk() {
        return "MIICCjCCAbCgAwIBAgICAeYwCgYIKoEcz1UBg3UwTTEcMBoGA1UEAwwTU00yIEludGVybWVkaWF0ZSBDQTEPMA0GA1UECwwGU0hVRFVOMQ8wDQYDVQQKDAZTSFVEVU4xCzAJBgNVBAYTAkNOMB4XDTIzMDkxNzAzMDQwNFoXDTI2MDkxNjAzMDQwNFowWDELMAkGA1UEBhMCQ04xDTALBgNVBAgMBG51bGwxDTALBgNVBAcMBG51bGwxDTALBgNVBAsMBG51bGwxDTALBgNVBAoMBG51bGwxDTALBgNVBAMMBG51bGwwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAAQHKBX786881tHipUD3QdbD4RT78HyRitqzKexIgJp/9BISZpbrThJHGSgbbAPyABeCZYfUvXc99C3U0gb6hohAo3UwczAdBgNVHQ4EFgQUjNQXL85qwQwEQ9ECv4C2Txa0w/MwHwYDVR0jBBgwFoAUoCHsae37q0cwbjzmuMaBvy1CT1MwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCAoQwEwYDVR0lBAwwCgYIKwYBBQUHAwgwCgYIKoEcz1UBg3UDSAAwRQIhAJkhbCSXyV6ll8PYbr14RPIT8jVFiTpDS4g9lc0q367xAiBjSV80bKQ1WDGIkZv1sr/neZiOrRhfoVptL4dgshaqsw==";
    }

    @Override
    public String getLocalSignSk() {
        return "MIICSwIBADCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8wRAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqeS89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvhcVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7///////////////9yA99rIcYFK1O79Ak51UEjAgEBBIIBVTCCAVECAQEEIGXsumPOF1qs8VmZLzj77X2hf7iqmkE1xCnCi9EdFLJLoIHjMIHgAgEBMCwGByqGSM49AQECIQD////+/////////////////////wAAAAD//////////zBEBCD////+/////////////////////wAAAAD//////////AQgKOn6np2fXjRNWp5Lz2UJp/OXifUVq4+S3by9QU2UDpMEQQQyxK4sHxmBGV+ZBEZqOcmUj+MLv/JmC+FxWkWJM0x0x7w3NqL09necWb3O42tpIVPQqYd8xipHQALfMuUhOfCgAiEA/////v///////////////3ID32shxgUrU7v0CTnVQSMCAQGhRANCAAQHKBX786881tHipUD3QdbD4RT78HyRitqzKexIgJp/9BISZpbrThJHGSgbbAPyABeCZYfUvXc99C3U0gb6hohA";
    }

    @Override
    public String getLocalEncPk() {
        return "MIICADCCAaagAwIBAgICAecwCgYIKoEcz1UBg3UwTTEcMBoGA1UEAwwTU00yIEludGVybWVkaWF0ZSBDQTEPMA0GA1UECwwGU0hVRFVOMQ8wDQYDVQQKDAZTSFVEVU4xCzAJBgNVBAYTAkNOMB4XDTIzMDkxNzAzMDQwNFoXDTI2MDkxNjAzMDQwNFowWDELMAkGA1UEBhMCQ04xDTALBgNVBAgMBG51bGwxDTALBgNVBAcMBG51bGwxDTALBgNVBAsMBG51bGwxDTALBgNVBAoMBG51bGwxDTALBgNVBAMMBG51bGwwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAAQ5bioBSD2fqZL/tja42BTR0+SqEtpw8L1U7HVsD5WnpEyegJEYgJpZdBE6/oYvKZiBQl8UzqRpesJ+e0pLdyz9o2swaTAdBgNVHQ4EFgQUulreNDYH5jEyhRfRkCTRFRvSD7gwHwYDVR0jBBgwFoAUoCHsae37q0cwbjzmuMaBvy1CT1MwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBDAwCQYDVR0lBAIwADAKBggqgRzPVQGDdQNIADBFAiEAhf27BGwnnM64UJm0Ca3JWzzoOsxt0qv/3gFXd3Q0oLoCIEPhUHGcJjWeASwL7Y9RrIIgJJzYyQC/WSxL8qQZ6PM6";
    }

    @Override
    public String getLocalEncSk() {
        return "MIICBQIBADCB7AYHKoZIzj0CATCB4AIBATAsBgcqhkjOPQEBAiEA/////v////////////////////8AAAAA//////////8wRAQg/////v////////////////////8AAAAA//////////wEICjp+p6dn140TVqeS89lCafzl4n1FauPkt28vUFNlA6TBEEEMsSuLB8ZgRlfmQRGajnJlI/jC7/yZgvhcVpFiTNMdMe8Nzai9PZ3nFm9zuNraSFT0KmHfMYqR0AC3zLlITnwoAIhAP////7///////////////9yA99rIcYFK1O79Ak51UEjAgEBBIIBDzCCAQsCAQEEIO8zMUdKLAssnNSNCxQIgfpbfg7Kovvr2plCfh93oKhGoIHjMIHgAgEBMCwGByqGSM49AQECIQD////+/////////////////////wAAAAD//////////zBEBCD////+/////////////////////wAAAAD//////////AQgKOn6np2fXjRNWp5Lz2UJp/OXifUVq4+S3by9QU2UDpMEQQQyxK4sHxmBGV+ZBEZqOcmUj+MLv/JmC+FxWkWJM0x0x7w3NqL09necWb3O42tpIVPQqYd8xipHQALfMuUhOfCgAiEA/////v///////////////3ID32shxgUrU7v0CTnVQSMCAQE=";
    }

    @Override
    public String getPeerSignPk() {
        return "MIICEjCCAbmgAwIBAgICAeQwCgYIKoEcz1UBg3UwTTEcMBoGA1UEAwwTU00yIEludGVybWVkaWF0ZSBDQTEPMA0GA1UECwwGU0hVRFVOMQ8wDQYDVQQKDAZTSFVEVU4xCzAJBgNVBAYTAkNOMB4XDTIzMDkxNzAyNTYyM1oXDTI2MDkxNjAyNTYyM1owYTELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB2JlaWppbmcxEDAOBgNVBAcMB2JlaWppbmcxDzANBgNVBAsMBnNodWR1bjEPMA0GA1UECgwGc2h1ZHVuMQwwCgYDVQQDDANib3kwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAAScCR0BgxlNURI7zt4582EyoyR0TPy6bTIl85OIMwmqlV9SV/nyC0eBM22OX/0kme8ISwIEz7UQaute3UpR/5Tko3UwczAdBgNVHQ4EFgQUAH7cVTXoqwqEQJ3QbDmUnk/zAAgwHwYDVR0jBBgwFoAUoCHsae37q0cwbjzmuMaBvy1CT1MwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCAoQwEwYDVR0lBAwwCgYIKwYBBQUHAwgwCgYIKoEcz1UBg3UDRwAwRAIgfRkki0Pwz2rLlY/dGU6/xmAaIs41Z4aq2Bn+o1YyhRoCIH3PQTpeT9KANTtaQxl1gfSClJhXKlChQl0CPgV64fa3";
    }

    @Override
    public String getPeerEncPk() {
        return "MIICCTCCAa+gAwIBAgICAeUwCgYIKoEcz1UBg3UwTTEcMBoGA1UEAwwTU00yIEludGVybWVkaWF0ZSBDQTEPMA0GA1UECwwGU0hVRFVOMQ8wDQYDVQQKDAZTSFVEVU4xCzAJBgNVBAYTAkNOMB4XDTIzMDkxNzAyNTYyM1oXDTI2MDkxNjAyNTYyM1owYTELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB2JlaWppbmcxEDAOBgNVBAcMB2JlaWppbmcxDzANBgNVBAsMBnNodWR1bjEPMA0GA1UECgwGc2h1ZHVuMQwwCgYDVQQDDANib3kwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAAS6Qkvxx9aKu5507pzBXgMMKComeICBDhgKlJWd7zBMrFLgdsX6fVNqmrzPcScLK9FbAuUgakRuZqHd5Dlo5oO6o2swaTAdBgNVHQ4EFgQUF98/kz90JMzn96QdMgCfgj1zKq0wHwYDVR0jBBgwFoAUoCHsae37q0cwbjzmuMaBvy1CT1MwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBDAwCQYDVR0lBAIwADAKBggqgRzPVQGDdQNIADBFAiEAyJ7v19C7Sj7PZ077dAxONTewnaE3E8GukaHCAjpP4gcCIGH2eOEn5LqXRzbyWJkOMfGbqnwA0fAT57uwdaEblNAM";
    }
}
